version: '3.7'
services:
  jenkins:
    build: ./
    image: mayur/jenkins:latest
    environment:
      DOCKER_SOCKET: /var/run/docker.sock
      DOCKER_GROUP: root           # change your DOCKER_GROUP to your sudo user or root
      JENKINS_USER: jenkins
      JENKINS_WORKSPACE: /var/jenkins_workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-home:/var/jenkins_home
      - ./jenkins-workspace:/var/jenkins_home/workspace
      # - ./aws:/var/jenkins_home/.aws:ro   # if you have awscli credentials to mount on jenkins_home
      # Container Timezone from Host Machine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "8080:8080"
    restart: always
    container_name: jenkins

# volumes:
#   jenkins-home:
#     external: true

# networks:
#   default:
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16
